/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Categories: typeof import('./src/components/Categories.vue')['default']
    Dialog: typeof import('./src/components/common/Dialog.vue')['default']
    ImportForm: typeof import('./src/components/ImportForm.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NetIncome: typeof import('./src/components/NetIncome.vue')['default']
    PopUp: typeof import('./src/components/common/PopUp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionRow: typeof import('./src/components/TransactionRow.vue')['default']
    Transactions: typeof import('./src/components/Transactions.vue')['default']
  }
}
