/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BudgetAnalysisCard: typeof import('./src/components/BudgetAnalysisCard.vue')['default']
    BudgetAnalysisDialog: typeof import('./src/components/BudgetAnalysisDialog.vue')['default']
    Categories: typeof import('./src/components/Categories.vue')['default']
    CategoryTable: typeof import('./src/components/common/CategoryTable.vue')['default']
    Dialog: typeof import('./src/components/common/Dialog.vue')['default']
    HeroBanner: typeof import('./src/components/common/HeroBanner.vue')['default']
    ImportForm: typeof import('./src/components/ImportForm.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NetIncome: typeof import('./src/components/NetIncome.vue')['default']
    NetTrend: typeof import('./src/components/NetTrend.vue')['default']
    PopUp: typeof import('./src/components/common/PopUp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavingsRate: typeof import('./src/components/SavingsRate.vue')['default']
    SectionHeader: typeof import('./src/components/common/SectionHeader.vue')['default']
    SurfaceCard: typeof import('./src/components/common/SurfaceCard.vue')['default']
    TransactionCountTable: typeof import('./src/components/TransactionCountTable.vue')['default']
    TransactionReviewDialog: typeof import('./src/components/TransactionReviewDialog.vue')['default']
    TransactionRow: typeof import('./src/components/TransactionRow.vue')['default']
    Transactions: typeof import('./src/components/Transactions.vue')['default']
    TransactionsTable: typeof import('./src/components/TransactionsTable.vue')['default']
  }
}
